services:
  postgres:
    image: postgres:latest
    container_name: hasura-mvp-db
    shm_size: 128mb
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      PGPORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./entrypoint/:/docker-entrypoint-initdb.d/
volumes:
  postgres-data:
